name: weather-new-action

on:
  push:
  schedule:
    - cron: "38 22 * * *" #早上6点45左右推送
  #workflow_dispatch:
    
jobs:
  bot:
    runs-on: ubuntu-latest
    steps:
      - uses: szenius/set-timezone@v1.0
        with:
          timezoneWindows: "China Standard Time"
          timezoneLinux: "Asia/Shanghai"
      - name: 'Checkout codes'
        uses: actions/checkout@v2
      - name: python env
        uses: actions/setup-python@v1
        with:
          python-version: 3.7
      # 安装依赖
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install setuptools wheel twine
          pip install bs4 lxml
      - name: 'Get DataSource'
        run: curl https://news.topurl.cn > ./result.html
      - name: 'Get Info'
        run: python ./getInfo.py
      - name: 'Get Date'
        run: |
          echo "REPORT_DATE=$(TZ=':Asia/Shanghai' date '+%Y-%m-%d %T')" >> $GITHUB_ENV
          echo "TODAY_DATE=$(TZ=':Asia/Shanghai' date +'%Y-%m-%d')" >> $GITHUB_ENV
      - name: 'Get TEXT'
        run: |
            echo 'FILE_TEXT<<EOF' >> $GITHUB_ENV
            cat ./result.txt >> $GITHUB_ENV
            echo 'EOF' >> $GITHUB_ENV
            
      - name: build success-'发送到钉钉群'
        if: ${{ success() }}
        uses: fifsky/dingtalk-action@master
        with:
          url: https://oapi.dingtalk.com/robot/send?access_token=${{ secrets.DINGTALK_WEBHOOK }}
          type: text
          at: all
          content: |
            ${{env.FILE_TEXT}}
            
      - name: 'Send mail'
        uses: dawidd6/action-send-mail@master
        with:
          server_address: smtp.qq.com
          server_port: 465
          username: ${{ secrets.MAIL_USER_NMAE }}
          password: ${{ secrets.MAIL_PWD }}
          subject: 今日新闻简报推送 (${{env.REPORT_DATE}})
          body: ${{env.FILE_TEXT}}
          to: ${{ secrets.MAIL_USER_NMAE }}
          from: news.topurl.cn
          content_type: text/html
                     
      - name: '打完收工,提交代码!'
        run: |
          git config --local user.email "${{ secrets.MAIL_USER_NMAE }}"
          git config --local user.name "Sirius2016"
          git remote set-url origin https://${{ github.actor }}:${{ secrets.MYGG_TOKEN }}@github.com/${{ github.repository }}
          git pull
          cp -Rf result.txt logs/${{env.TODAY_DATE}}.txt
          git add .
          git commit -m "Update By Github Action Bot"
          git push -u origin main